jdbc.url=jdbc:h2:./paoj-2026-db;DB_CLOSE_DELAY=-1;MODE=MYSQL
jdbc.username=sa
jdbc.password=
jdbc.driverClassName=org.h2.Driver
jdbc.maxPoolSize=10
jdbc.schema=resources/schema.sql

db.url=jdbc:h2:./paoj-2026-db;DB_CLOSE_DELAY=-1;MODE=MYSQL
db.user=sa
db.password=

